target:
  os: os.linux.csos
  capabilities:
    - security.lsm.selinux
  dependencies:
    - dns

replicationType: "deployment"

containers:
  - image: mysql:8
    name: mysql
    version: 8.0.16
    digest:
      sha256: 711df5b93720801b3a727864aba18c2ae46c07f9fe33d5ce9c1f5cbc2c035101

    policies:
      - policy/example.te

    resources:
      limit:
        cpu: 250m # == 1000m
        memory: 256Mi # E, P, T, G, M, K, Ei, Pi, Ti, Gi, Mi, Ki
      request:
        cpu: 100m
        memory: 128Mi

    services:
      - type: LoadBalancer
        ports:
        - protocol: TCP
          port: 3306

    ports:
      - protocol: TCP
        port: 3306
        
    env:
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: true
      - name: MYSQL_USER
        value: mysql-config{database.user}
        type: config
      - name: MYSQL_DATABASE
        value: mysql-config{database.db}
        type: config
      - name: MYSQL_ROOT_PASSWORD
        value: mysql-secrets{database.password}
        type: secret

configs:
  - name: mysql-config
    data:
    - key: database.db
      data: ${database_db}
    - key: database.user
      data: ${database_user}

secrets:
  - name: mysql-secrets
    data:
    - key: database.password # password must match what is in 'database.password'
      data: ${root_password} #postgres://drone:db-pw-change-me.secret@postgres-service:5432/postgres?sslmode=disable
